# dbt_project.yml
name: omd_dbt_pg
version: 1.0.0
config-version: 2
profile: default

# Quote schema because it has a hyphen
quoting:
  database: false
  schema: true
  identifier: false

models:
  omd_dbt:
    +database: dtr_sandbox
    +schema: dbt-omd-pg
    +materialized: view

    staging:
       +schema: stg
    intermediate:
       +schema: int
    marts:
       +schema: mart
