# dbt_project.yml
name: omd_dbt                # <-- underscore, no hyphen
version: 1.0.0
config-version: 2
profile: default             # <-- matches your profiles.yml

# Quote schema because it has a hyphen
quoting:
  database: false            # catalog
  schema: true               # needed for `dbt-omd`
  identifier: false

models:
  omd_dbt:                   # <-- must match `name:` above
    +database: dtr_sandbox   # database == catalog
    +schema: dbt-omd         # will be backtick-quoted
    +materialized: view      # or table if you prefer

    # If these cause CREATE on catalog (and you lack privileges), keep them commented
    # until those schemas exist or you have grants.
    # staging:
    #   +schema: stg
    # intermediate:
    #   +schema: int
    # marts:
    #   +schema: mart
