default:
  target: dev
  outputs:
    dev:
      type: databricks
      host: <your-databricks-host>
      http_path: <your-databricks-http-path>
      token: <your-databricks-personal-access-token>
      schema: <your-schema-name>
      database: <your-database-name>
      threads: 1
      catalog: hive_metastore