default:
  target: dev
  outputs:
    dev:
      type: databricks
      host: adb-3020218199835395.15.azuredatabricks.net
      http_path: /sql/1.0/warehouses/645d6cc8044bd264
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      schema: dbt-omd
      threads: 4